#!/bin/bash

docker build -t zergling ./services/ZerglingService
docker build -t hydralisk ./services/HydraliskService
docker build -t hydralisk-dev -f ./services/HydraliskService/Dockerfile.dev ./services/HydraliskService