version: '2'
services:
    zergling:
        build: ../services/ZerglingService
        volumes: 
            - ../services/ZerglingService:/app
        ports:
            - "8080:3000"
        links: 
            - hydralisk
        environment:
            - NODE_ENV=docker
        command: ./node_modules/.bin/nodemon -L app.js
    hydralisk:
        build: ../services/HydraliskService
        volumes: 
            - ../services/HydraliskService:/app
        environment:
            - NODE_ENV=docker
        command: ./node_modules/.bin/nodemon -L app.js
        extra_hosts:
            - "dockerhost:$DOCKERHOST"
    background:
        build: ../services/BackgroundService
        volumes: 
            - ../services/BackgroundService:/app
        environment:
            - NODE_ENV=docker
        command: ./node_modules/.bin/nodemon -L app.js
        extra_hosts:
            - "dockerhost:$DOCKERHOST"