apiVersion: v1
kind: Service
metadata:
  labels:
    app: zergling
  name: zergling
  namespace: default
spec:
  ports:
  - name: tcp-3000-3000-9jrn3
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: zergling
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}